spring.application.name=pgw

spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=postgres
spring.datasource.password=ugwonna
spring.sql.init.mode=always

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081

# Bank/acquirer service this gateway
bank.api.base-url=${BANK_API_BASE_URL:http://localhost:8787/api/v1}
